version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup dependencies
          command: |
            echo "export PIPENV_VENV_IN_PROJECT=1" >> $BASH_ENV
            echo "export PIPENV_IGNORE_VIRTUALENVS=1" >> $BASH_ENV

            echo '== which pip ============================================='
            which pip
            echo '== which python =========================================='
            which python
            echo '== python --version ======================================'
            python --version
            echo '== pipenv lock -d --requirements ========================='
            pipenv lock -d --requirements | tee requirements.txt
            echo '== pipenv sync -d ========================================'
            pipenv sync -d
            echo '=========================================================='

      - save_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
            - .venv

      - run:
          name: Check
          command: pipenv run peltak check

      - run:
          name: Test
          command: pipenv run peltak test

      - run:
          name: Build Documentation
          command: |
            pipenv run peltak docs --recreate --run-doctests
            mv docs/html docs/jwtlib-docs
            cd docs && zip -r ../.build/jwtlib-docs.zip jwtlib-docs

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: .build/jwtlib-docs.zip
          destination: jwtlib-docs.zip

  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup
          command: |
            echo "export PIPENV_VENV_IN_PROJECT=1" >> $BASH_ENV
            echo "export PIPENV_IGNORE_VIRTUALENVS=1" >> $BASH_ENV

            echo '== pipenv sync -d ========================================'
            pipenv sync -d

      - run:
          name: Upload to pypi
          command: |
            pipenv run peltak pypi configure
            pipenv run peltak pypi upload
            rm ~/.pypirc

      - run:
          name: Create release tag
          command: |
            pipenv run peltak release tag -m "$(pipenv run peltak changelog)"
            git push origin v$(pipenv run peltak version --porcelain)

# docs:
#   docker:
#     - image: novopl/python36:ci-alpine
#   steps:
#     - checkout
#     - restore_cache:
#         key: deps-rev1-{{ checksum "setup.py" }}

#     - run:
#         name: Setup
#         command: |
#           pip install .
#           peltak --help

#     - run:
#         name: Deploy gh-pages
#         command: |
#           peltak docs
#           git checkout gh-pages
#           cp -r docs/html/* ./
#           git add .
#           git config user.email ${GIT_EMAIL}
#           git config user.name ${GIT_USER}
#           git commit -nm "Docs build #${CIRCLECI_BUILD_NUM}"
#           git push --no-verify origin gh-pages


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: [gh-pages]
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
              ignore: [gh-pages]
#     - docs:
#         requires:
#           - build
#         filters:
#           branches:
#             only: master
